In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
## Load libraries
import pandas as pd
import numpy as np

In [3]:
# Display options
pd.set_option('display.max_columns',50)

In [6]:
test_data.shape
test_data.head(2)

(271, 45)

,match id,team1,team1_id,team1_roster_ids,team2,team2_id,team2_roster_ids,toss winner,toss decision,venue,city,match_dt,lighting,series_name,season,ground_id,team_count_50runs_last15,team_winp_last5,team1only_avg_runs_last15,team1_winp_team2_last15,ground_avg_runs_last15,team_count_4runs_last15,team_count_6runs_last15,avg_stkrate,avg_runs,avg_balls_faced,avg_caught,avg_bowled,avg_lbw,avg_run out,avg_stumped,runs_consistency,strike_rate_consistency,boundary_percentage,avg_wicket_count,avg_economy,avg_maiden,avg_dots,avg_Fours,avg_Sixes,avg_wides,avg_noballs,dot_ball_percentage_ratio,wicket_to_run_ratio,avg_bowling_strike_rate
0,9250275,Jy,28594,7438955.0:8271969.0:8369661.0:3685247.0:259025...,Ud Ss of Aa,90,2436944.0:8117500.0:6703528.0:3010748.0:161387...,Ud Ss of Aa,field,Bo Ac Cb,Bulawayo,2022-07-11,day match,Ud Ss of Aa tr of Ze,2022,3226,0.000000,0.019608,NaN,0.00,NaN,0.166667,0.142857,0.745558,0.505515,0.126984,0.285714,1.000000,0.500,1.000000,1.000000,0.170240,0.366911,1.031621,0.045455,0.104299,0.933333,0.106870,0.250000,0.500000,0.437500,1.000000,0.711823,0.950935,0.067742
1,9262189,Ga An Ws,36084,3715690.0:6818622.0:4069666.0:393014.0:4690188...,Ja Ts,36098,4690258.0:3761246.0:8464385.0:5742470.0:315072...,Ja Ts,field,Pe Sm Ga,Providence,2022-09-21,night match,Cn Pr Le,2022,13915,0.615385,0.344262,151.285714,66.67,153.5,0.945355,0.937984,1.062096,0.993186,0.891282,0.896104,1.090909,0.625,0.727273,1.333333,0.984319,1.190884,1.015238,0.828283,1.074122,0.989485,0.997905,1.035294,1.108978,1.110933,1.095737,1.012563,1.001180,0.912182

In [7]:
train_data['winner_01'] = train_data.apply(lambda x: 1 if (x['team2']==x['winner']) else 0, axis=1)

In [8]:
## Toss winner to numerical - 1 if team2 wins, else 0

train_data['toss_winner_01'] = np.where(train_data['toss winner']==train_data['team2'], 1, 0)
test_data['toss_winner_01'] = np.where(test_data['toss winner']==test_data['team2'], 1, 0)

In [9]:
## Toss decision - categorical - 1 if winner bats, 0 otherwise

train_data['toss_decision_01'] = np.where(train_data['toss decision']=='bat', 1, 0)
test_data['toss_decision_01'] = np.where(test_data['toss decision']=='bat', 1, 0)

In [10]:
X,y = train_data[['toss_winner_01','toss_decision_01','team_count_50runs_last15','team_winp_last5','team1only_avg_runs_last15','team1_winp_team2_last15','ground_avg_runs_last15','team_count_4runs_last15','team_count_6runs_last15','avg_stkrate','avg_runs','avg_balls_faced','avg_caught','avg_bowled','avg_lbw','avg_run out','avg_stumped','runs_consistency','strike_rate_consistency','boundary_percentage','avg_wicket_count',
                 'avg_economy','avg_maiden','avg_dots','avg_wides','avg_Fours','avg_Sixes',
                 'avg_noballs','dot_ball_percentage_ratio','avg_bowling_strike_rate']], train_data['winner_01']

In [11]:
y.head()

0    1
1    0
2    0
3    0
4    1
Name: winner_01, dtype: int64

In [12]:
X.head()

,toss_winner_01,toss_decision_01,team_count_50runs_last15,team_winp_last5,team1only_avg_runs_last15,team1_winp_team2_last15,ground_avg_runs_last15,team_count_4runs_last15,team_count_6runs_last15,avg_stkrate,avg_runs,avg_balls_faced,avg_caught,avg_bowled,avg_lbw,avg_run out,avg_stumped,runs_consistency,strike_rate_consistency,boundary_percentage,avg_wicket_count,avg_economy,avg_maiden,avg_dots,avg_wides,avg_Fours,avg_Sixes,avg_noballs,dot_ball_percentage_ratio,avg_bowling_strike_rate
0,1,0,1.666667,0.672131,139.000000,100.0,157.178571,1.555556,1.642857,0.904734,0.791258,1.424594,2.222222,1.666667,2.000000,0.333333,0.666667,0.937386,0.890493,1.039725,1.641026,0.918698,0.952020,0.811936,0.733951,0.636585,1.084815,1.050000,0.972378,1.080726
1,1,0,1.285714,1.952381,156.000000,50.0,103.500000,1.248227,0.593496,0.864729,0.924091,1.033629,0.890625,1.117647,1.125000,1.333333,3.500000,0.985868,0.841438,0.968076,0.822430,0.973906,0.966806,0.958504,0.688571,1.036431,0.990274,1.048005,0.977765,1.087540
2,1,0,0.857143,0.672131,173.266667,0.0,154.333333,1.025381,0.786408,1.054596,1.097576,0.979472,0.757143,1.111111,0.875000,0.666667,0.200000,1.043717,0.668827,0.980600,1.115385,0.950756,1.052298,1.229018,1.109531,1.030837,1.019334,1.026316,1.029208,0.992289
3,0,1,2.166667,1.975610,164.266667,50.0,144.250000,1.289308,1.702128,1.207829,1.477689,1.366240,0.880597,1.050000,0.909091,2.333333,0.333333,1.198114,0.989524,0.995573,0.818966,0.972759,0.995548,1.043557,1.096979,0.974138,1.002037,1.015984,1.003735,1.019218
4,1,0,0.818182,1.327869,164.666667,0.0,189.000000,0.891304,1.258824,1.086959,0.820736,1.062331,1.129032,1.307692,1.400000,1.300000,1.500000,0.860648,1.349231,0.992196,1.100000,1.015838,1.044850,0.975527,1.022556,1.063073,0.985306,1.046014,0.998965,1.090007

In [13]:
X_test = test_data[X.columns.tolist()]

In [14]:
X_nans = X.isna().sum().reset_index()
X_nans[X_nans[0]!=0]

X_test_nans = X_test.isna().sum().reset_index()
X_test_nans[X_test_nans[0]!=0]

                        index    0
4   team1only_avg_runs_last15   21
6      ground_avg_runs_last15   53
18    strike_rate_consistency  100

                        index   0
4   team1only_avg_runs_last15   7
6      ground_avg_runs_last15  10
18    strike_rate_consistency  27

In [15]:
X.fillna(0, inplace=True)
X_test.fillna(0, inplace=True)

/tmp/ipykernel_11894/1698769224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.fillna(0, inplace=True)
/tmp/ipykernel_11894/1698769224.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test.fillna(0, inplace=True)

In [16]:
X_nans = X.isna().sum().reset_index()
X_nans[X_nans[0]!=0]

X_test_nans = X_test.isna().sum().reset_index()
X_test_nans[X_test_nans[0]!=0]

Empty DataFrame
Columns: [index, 0]
Index: []

Empty DataFrame
Columns: [index, 0]
Index: []

In [17]:
X['toss_winner_01'].value_counts()
X['toss_decision_01'].value_counts()
X['team_count_50runs_last15'].describe()

1    620
0    328
Name: toss_winner_01, dtype: int64

0    617
1    331
Name: toss_decision_01, dtype: int64

count    948.000000
mean       1.202602
std        1.008793
min        0.083333
25%        0.686678
50%        1.000000
75%        1.400000
max       11.000000
Name: team_count_50runs_last15, dtype: float64

In [19]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import classification_report

In [20]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split

In [22]:
X_train.head()

,toss_winner_01,toss_decision_01,team_count_50runs_last15,team_winp_last5,team1only_avg_runs_last15,team1_winp_team2_last15,ground_avg_runs_last15,team_count_4runs_last15,team_count_6runs_last15,avg_stkrate,avg_runs,avg_balls_faced,avg_caught,avg_bowled,avg_lbw,avg_run out,avg_stumped,runs_consistency,strike_rate_consistency,boundary_percentage,avg_wicket_count,avg_economy,avg_maiden,avg_dots,avg_wides,avg_Fours,avg_Sixes,avg_noballs,dot_ball_percentage_ratio,avg_bowling_strike_rate
109,1,0,0.875000,1.000000,166.090909,0.0,155.6000,0.937063,1.016667,1.124456,1.170111,0.798913,0.644068,1.300000,0.857143,0.428571,1.200000,0.994808,1.009707,1.019730,0.845070,0.983252,0.945236,1.024277,0.893300,1.076184,0.980645,0.956357,0.977877,1.017776
77,1,0,2.833333,3.857143,165.066667,50.0,163.6000,1.425373,1.654545,0.989242,1.186946,1.439863,1.229167,1.187500,1.500000,1.166667,3.000000,1.173011,0.953715,1.000387,1.164557,0.893946,1.009759,1.064103,0.790608,0.784397,0.895493,0.984190,1.029033,0.878920
549,1,0,1.125000,0.405941,171.266667,0.0,167.3000,1.057895,1.054348,0.935106,1.234244,1.083427,0.919355,0.478261,0.363636,0.833333,2.000000,1.099578,0.898676,1.001541,0.793388,0.981931,1.001535,1.108672,1.022021,1.055625,0.970588,1.057801,1.010215,1.054964
798,1,0,2.000000,21.000000,157.600000,25.0,0.0000,1.082278,1.688525,0.951593,0.998248,1.187955,1.095238,1.357143,1.333333,0.857143,1.666667,1.091305,0.981758,1.026382,1.575342,0.978583,1.003643,0.954713,0.862323,0.908379,0.916025,1.013990,1.005641,0.787928
82,0,1,2.125000,0.344262,174.933333,0.0,159.4375,1.342857,2.126582,1.156045,1.177244,1.315789,1.104478,1.125000,1.500000,0.500000,1.333333,1.247368,1.238376,1.068327,1.666667,1.001796,1.001684,1.276875,1.202810,1.006859,1.217089,1.031680,1.064540,0.609415

In [27]:
features = ['toss_winner_01','toss_decision_01','team_count_50runs_last15','team_winp_last5',
            'team1only_avg_runs_last15','team1_winp_team2_last15','ground_avg_runs_last15',
            'team_count_4runs_last15','team_count_6runs_last15','avg_stkrate','avg_runs',
            'avg_balls_faced','avg_caught','avg_bowled','avg_lbw','avg_run out','avg_stumped',
            'runs_consistency','strike_rate_consistency','boundary_percentage','avg_wicket_count',
            'avg_economy','avg_maiden','avg_dots','avg_wides','avg_Fours','avg_Sixes','avg_noballs',
            'dot_ball_percentage_ratio','avg_bowling_strike_rate']

# Assuming the target variable is run_difference or a similar metric
target = 'run_difference'  # Replace with your actual target variable

In [28]:
features

['toss_winner_01',
 'toss_decision_01',
 'team_count_50runs_last15',
 'team_winp_last5',
 'team1only_avg_runs_last15',
 'team1_winp_team2_last15',
 'ground_avg_runs_last15',
 'team_count_4runs_last15',
 'team_count_6runs_last15',
 'avg_stkrate',
 'avg_runs',
 'avg_balls_faced',
 'avg_caught',
 'avg_bowled',
 'avg_lbw',
 'avg_run out',
 'avg_stumped',
 'runs_consistency',
 'strike_rate_consistency',
 'boundary_percentage',
 'avg_wicket_count',
 'avg_economy',
 'avg_maiden',
 'avg_dots',
 'avg_wides',
 'avg_Fours',
 'avg_Sixes',
 'avg_noballs',
 'dot_ball_percentage_ratio',
 'avg_bowling_strike_rate']

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X[features], X[target], test_size=0.2, random_state=42)

KeyError: 'run_difference'